In [1]:
# 1
# Create a 1D NumPy array with numbers from 1 to 10
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# 2
# Create a NumPy array of zeros of size 5
import numpy as np
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [3]:
# 3
# Create a NumPy array of ones of size 4x4
import numpy as np
a = np.ones((4, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# 4
# Create an array of even numbers from 2 to 20
import numpy as np
a = np.arange(2, 21, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# 5
# Create an array with values from 10 to 50 step 5
import numpy as np
a = np.arange(10, 51, 5)
print(a)

[10 15 20 25 30 35 40 45 50]


In [6]:
# 6
# Create an array and multiply by 3
import numpy as np
a = np.array([1, 2, 3])
print(a * 3)

[3 6 9]


In [7]:
# 7
# Create two arrays and add element-wise
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [8]:
# 8
# Find the mean of an array
import numpy as np
a = np.array([10, 20, 30, 40])
print(np.mean(a))

25.0


In [9]:
# 9
# Find square root of each element
import numpy as np
a = np.array([4, 9, 16, 25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [10]:
# 10
# Create random array and find sum
import numpy as np
a = np.random.randint(1, 100, 5)
print(a)
print(np.sum(a))

[12 85 92 14 97]
300


In [11]:
# 11
# Slice first 5 elements
import numpy as np
a = np.arange(1, 11)
print(a[:5])

[1 2 3 4 5]


In [12]:
# 12
# Get last two elements
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(a[-2:])

[40 50]


In [13]:
# 13
# Change 3rd element to 99
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a[2] = 99
print(a)

[ 1  2 99  4  5]


In [14]:
# 14
# Access element in 2nd row 3rd column
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a[1][2])

6


In [15]:
# 15
# Reverse a 1D array using slicing
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a[::-1])

[5 4 3 2 1]


In [16]:
# 16
# Generate a random integer between 1 and 100
import numpy as np
a = np.random.randint(1, 101)
print(a)

78


In [17]:
# 17
# Generate random 3x3 array
import numpy as np
a = np.random.randint(1, 100, (3, 3))
print(a)

[[78 32 82]
 [27 42 79]
 [92 68 72]]


In [18]:
# 18
# Generate 5 random numbers from normal distribution
import numpy as np
a = np.random.randn(5)
print(a)

[-0.00257969 -0.47780604  0.1785734  -1.26633753  1.88145264]


In [19]:
# 19
# Generate 10 random numbers between 0 and 1
import numpy as np
a = np.random.rand(10)
print(a)

[0.33312854 0.32520605 0.19468933 0.98986381 0.74431166 0.95906506
 0.58766866 0.51504814 0.82066978 0.15234256]


In [20]:
# 20
# Shuffle an array randomly
import numpy as np
a = np.array([1, 2, 3, 4, 5])
np.random.shuffle(a)
print(a)

[4 1 2 5 3]


In [21]:
# 21
# Transpose a 2x3 matrix
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
# 22
# Reshape 1D array into 3x4
import numpy as np
a = np.arange(1, 13)
b = a.reshape(3, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# 23
# Resize 1D array of size 5 into 3x3
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [24]:
# 24
# Convert 2D array into 1D
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]
